############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

# [[main]]
# name = "Elements"
# url = "elements/"
# weight = 3

[[main]]
name = "Education"
url = "education/"
weight = 3



[[main]]
name = "Research"
url = "Research/"
weight = 4



[[main]]
name = "Blog"
url = "blog/"
weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 6





# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1


[[footer]]
name = "Contact"
url = "contact/"
weight = 2

