############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

# [[main]]
# name = "Elements"
# url = "elements/"
# weight = 3

[[main]]
weight = 4
name = "Education"
weight = 3
hasChildren = true

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
name = "Contact"
url = "contact/"
weight = 5

[[main]]
parent = "Pages"
name = "Authors"
url = "authors/"




# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1


[[footer]]
name = "Contact"
url = "contact/"
weight = 2

